### ISSUE TITLE
Stage 3 syntax review

### ISSUE THREAD

**Issue by waldemarhorwat** [tc39/proposal-import-assertions#94]
The syntax seems fine. I have one question: Why can't the list of AssertEntries be empty?

**Comment by waldemarhorwat** [comment]
Sorry, this should be stage 3 review not 2.

**Comment by ljharb** [comment]
why have assertion syntax if you aren't asserting anything?

there is `export {}` and `const {} = obj`, but both seem pretty confusing to have allowed :-/

**Comment by michaelficarra** [comment]
@ljharb Maybe you've commented them all out.

**Comment by dandclark** [comment]
Normally I'd be skeptical about allowing empty AssertEntries given the potential for confusion and the minor extra complexity with minimal benefit.  In other contexts people probably wouldn't expect an empty assert statement/function to be permitted.

But since we allow `import {} from "./foo.js"`, `export {}`, etc I think it might make sense to allow allow an empty AssertEntries for consistency's sake:
```mjs
import { } from "./foo.js" assert { }; // No error. Would be potentially surprising if the first
                                       // set of empty brackets was allowed but not the second.
```

**Comment by dandclark** [comment]
If we want to go this route, I created #95.  Other proposal champions, @ljharb, any strong opposition to this?  I'm lightly in favor for the consistency reason stated in my previous comment.

**Comment by MylesBorins** [comment]
I'm going to reopen this for now as I don't think we've gotten a +1 for all review. @dandclark please reclose if that was a mistake

**Comment by waldemarhorwat** [comment]
The revised syntax looks good.

**Comment by littledan** [comment]
The proposal reached stage 3, so re-closing
